<#
.SYNOPSIS
    Builds the combined Moxie Windows installer: desktop app + CLI in one NSIS
    setup executable, with the CLI added to the user PATH.
.DESCRIPTION
    Builds both Windows CLI binaries (amd64 + arm64), then runs the Wails NSIS
    build with a single combined installer (nsisType=single) so one download
    works on either architecture. Per-user install (no UAC), WebView2
    bootstrapper embedded by Wails, terminal `moxie` on PATH.

    The per-build values the NSIS template needs are written to
    desktop/build/windows/installer/moxie_build.nsh, and the two CLI binaries
    are staged next to it as moxie-cli-amd64.exe / moxie-cli-arm64.exe before
    `wails build` runs makensis.

    Prerequisites on the build machine: Go 1.26+, Node/npm (Wails frontend),
    the Wails CLI (go install github.com/wailsapp/wails/v2/cmd/wails@<version>)
    and NSIS (makensis on PATH).
.PARAMETER Version
    Version string stamped into both binaries (e.g. 0.4.0 or dev-abc1234).
    Defaults to `git describe --tags --always --dirty`.
.PARAMETER Channel
    Release channel: "main" (default) or "dev". The dev channel names binaries
    and the data directory with a -dev suffix and never collides with stable.
.PARAMETER OutputDir
    Where the finished installer is copied. Defaults to <repo>/dist.
.PARAMETER KeepStaging
    Keep the generated moxie_build.nsh and staged CLI binaries after the build.
.EXAMPLE
    .\scripts\package-windows.ps1 -Version 0.4.0
    .\scripts\package-windows.ps1 -Version dev-abc1234 -Channel dev
#>
[CmdletBinding()]
param(
    [string]$Version,
    [ValidateSet('main', 'dev')]
    [string]$Channel = 'main',
    [string]$OutputDir,
    [switch]$KeepStaging
)

$ErrorActionPreference = 'Stop'

function Write-Step { Write-Host "==> $args" -ForegroundColor Cyan }
function Write-Ok   { Write-Host "==> $args" -ForegroundColor Green }
function Write-Info { Write-Host "    $args" -ForegroundColor DarkGray }
function Write-Die  { param([string]$Message) Write-Host "==> $Message" -ForegroundColor Red; exit 1 }

$Root        = Split-Path -Parent $PSScriptRoot
$InstallerD  = Join-Path $Root 'desktop\build\windows\installer'
$DesktopDir  = Join-Path $Root 'desktop'
$NshPath     = Join-Path $InstallerD 'moxie_build.nsh'

if (-not $OutputDir) { $OutputDir = Join-Path $Root 'dist' }
if (-not (Test-Path -LiteralPath (Join-Path $Root 'go.mod'))) {
    Write-Die "No go.mod in $Root - run this from a moxie checkout."
}

# ── Toolchain checks ─────────────────────────────────────────────────────────
foreach ($tool in 'go', 'wails', 'makensis') {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        Write-Die "$tool was not found on PATH. Install Go 1.26+, the Wails CLI, and NSIS."
    }
}

# ── Version ──────────────────────────────────────────────────────────────────
if (-not $Version) {
    try {
        $desc = & git -C $Root describe --tags --always --dirty 2>$null
        if ($LASTEXITCODE -eq 0 -and $desc) { $Version = "$desc".Trim() }
    } catch { }
    if (-not $Version) { $Version = 'dev' }
}

# NSIS VIProductVersion needs a numeric major.minor.patch.
$numeric = '0.0.0'
if ($Version -match '(\d+)\.(\d+)\.(\d+)') {
    $numeric = "$($Matches[1]).$($Matches[2]).$($Matches[3])"
}

# ── Channel-specific names ───────────────────────────────────────────────────
if ($Channel -eq 'dev') {
    $productName = 'Moxie Dev'
    $setupName   = 'Moxie-Dev-Setup'
    $cliExe      = 'moxie-dev.exe'
    $desktopExe  = 'moxie-dev-desktop.exe'
} else {
    $productName = 'Moxie'
    $setupName   = 'Moxie-Setup'
    $cliExe      = 'moxie.exe'
    $desktopExe  = 'moxie-desktop.exe'
}

Write-Step "Packaging $productName installer ($Channel) version $Version"
Write-Info "numeric (NSIS/VIProductVersion): $numeric"

# ── Build the CLI for both Windows architectures ─────────────────────────────
$ldflags = "-s -w -X main.version=$Version -X main.channel=$Channel"
$staged = [ordered]@{
    amd64 = Join-Path $InstallerD 'moxie-cli-amd64.exe'
    arm64 = Join-Path $InstallerD 'moxie-cli-arm64.exe'
}
foreach ($arch in @('amd64', 'arm64')) {
    $out = $staged[$arch]
    Write-Step "Building CLI (windows/$arch)"
    $env:CGO_ENABLED = '0'
    $env:GOOS = 'windows'
    $env:GOARCH = $arch
    Push-Location $Root
    try {
        & go build -ldflags $ldflags -o $out .
        if ($LASTEXITCODE -ne 0) { Write-Die "CLI build failed for windows/$arch." }
    } finally {
        Pop-Location
        Remove-Item Env:CGO_ENABLED, Env:GOOS, Env:GOARCH -ErrorAction SilentlyContinue
    }
}

# ── Generate the NSIS defines file ───────────────────────────────────────────
$nsh = @"
; Generated by scripts/package-windows.ps1 - do not edit.
!define MOXIE_CHANNEL "$Channel"
!define MOXIE_VERSION "$numeric"
!define MOXIE_PRODUCT_NAME "$productName"
!define MOXIE_SETUP_NAME "$setupName"
!define MOXIE_CLI_EXE "$cliExe"
!define MOXIE_DESKTOP_EXE "$desktopExe"
!define MOXIE_CLI_AMD64 "moxie-cli-amd64.exe"
!define MOXIE_CLI_ARM64 "moxie-cli-arm64.exe"
"@
Set-Content -LiteralPath $NshPath -Value $nsh -Encoding ASCII
Write-Ok 'Generated moxie_build.nsh'

# ── Wails build: both arches, single combined NSIS installer, per-user ───────
Write-Step 'Building desktop app + NSIS installer (wails build --nsis)'
$wailsArgs = @(
    'build',
    '-platform', 'windows/amd64,windows/arm64',
    '-nsis',
    '-installscope', 'user',
    '-ldflags', "-X main.appVersion=$Version -X main.channel=$Channel"
)
Push-Location $DesktopDir
try {
    & wails @wailsArgs
    if ($LASTEXITCODE -ne 0) { Write-Die 'wails build failed.' }
} finally {
    Pop-Location
}

# ── Collect the installer ────────────────────────────────────────────────────
$built = Join-Path $Root "desktop\build\bin\$setupName.exe"
if (-not (Test-Path -LiteralPath $built)) {
    Write-Die "Expected installer not found at $built"
}
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$dest = Join-Path $OutputDir "$setupName.exe"
Copy-Item -LiteralPath $built -Destination $dest -Force
$sizeMB = [math]::Round((Get-Item $dest).Length / 1MB, 1)
Write-Ok "Installer: $dest ($sizeMB MB)"

# ── Publish raw desktop binaries for the stable in-app self-updater ──────────
# desktop/app.go's binaryName() looks for moxie-desktop-windows-<arch>.exe; the
# dev channel deliberately does not self-update, so only publish them for main.
if ($Channel -eq 'main') {
    foreach ($arch in @('amd64', 'arm64')) {
        $raw = Join-Path $Root "desktop\build\bin\moxie-$arch.exe"
        if (Test-Path -LiteralPath $raw) {
            $rawDest = Join-Path $OutputDir "moxie-desktop-windows-$arch.exe"
            Copy-Item -LiteralPath $raw -Destination $rawDest -Force
            Write-Ok "Desktop update asset: $rawDest"
        } else {
            Write-Info "WARN: desktop binary not found for self-update asset: $raw"
        }
    }
}

# ── Cleanup staging ──────────────────────────────────────────────────────────
if (-not $KeepStaging) {
    Remove-Item -LiteralPath $staged['amd64'], $staged['arm64'] -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $NshPath -Force -ErrorAction SilentlyContinue
}

Write-Host ''
Write-Ok "$productName $Version installer ready."
Write-Info "Channel: $Channel   Install dir: %LOCALAPPDATA%\Programs\$productName"
Write-Info "Installs: $desktopExe (GUI) + $cliExe (on PATH)"
