// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {coverart} from '../models';
import {db} from '../models';
import {context} from '../models';

export function AddGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function AddGameFromF95Zone(arg1:string,arg2:string,arg3:string):Promise<number>;

export function AddGameToCollection(arg1:number,arg2:number):Promise<void>;

export function AddScanPath(arg1:string):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function BrowseF95Zone(arg1:number,arg2:string):Promise<main.F95BrowsePage>;

export function CancelGameUpdate():Promise<boolean>;

export function CancelGameUpdateFor(arg1:number):Promise<boolean>;

export function CancelSync():Promise<boolean>;

export function CheckDependencies():Promise<Array<main.DependencyStatus>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateCollection(arg1:string):Promise<number>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DetectGame(arg1:string):Promise<main.DetectionResult>;

export function DownloadAllUpdates():Promise<void>;

export function DownloadGameUpdate(arg1:number):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function EditGame(arg1:number,arg2:main.EditGameFields):Promise<void>;

export function FetchCovers():Promise<void>;

export function FindCoverCandidates(arg1:number):Promise<Array<coverart.Candidate>>;

export function FindDuplicateGames():Promise<Array<main.DuplicateGroup>>;

export function GetAllDownloadLinks():Promise<Array<main.DesktopDownloadLinkWithGame>>;

export function GetCollectionGames(arg1:number):Promise<Array<main.DesktopGameSummary>>;

export function GetCollections():Promise<Array<main.DesktopCollection>>;

export function GetConfigDir():Promise<string>;

export function GetCookieStatus():Promise<string>;

export function GetCoverArtSettings():Promise<main.CoverArtSettings>;

export function GetCoverBaseURL():Promise<string>;

export function GetDbPath():Promise<string>;

export function GetGameCollections(arg1:number):Promise<Array<main.DesktopCollection>>;

export function GetGameCount():Promise<number>;

export function GetGameDetail(arg1:number):Promise<main.DesktopGameDetail>;

export function GetGameDownloadLinks(arg1:number):Promise<Array<main.DesktopDownloadLink>>;

export function GetGameDownloadLinksForUpdate(arg1:number):Promise<db.DownloadLink>;

export function GetGames():Promise<Array<main.DesktopGameSummary>>;

export function GetGamesWithDownloadLinks():Promise<Array<main.DesktopGameSummary>>;

export function GetInstallTargets():Promise<Array<main.InstallTarget>>;

export function GetOrganizeInstalls():Promise<boolean>;

export function GetScanPaths():Promise<Array<string>>;

export function GetStartupError():Promise<string>;

export function GetThreadPreview(arg1:string):Promise<main.ThreadPreview>;

export function GetUpdatableCount():Promise<number>;

export function GetUpdatableGames():Promise<Array<main.DesktopGameSummary>>;

export function GetUpdateConcurrency():Promise<number>;

export function GetVersion():Promise<string>;

export function InstallGame(arg1:number,arg2:string):Promise<void>;

export function ListDeletedGames():Promise<Array<main.DesktopGameSummary>>;

export function OpenDownloadURL(arg1:number):Promise<void>;

export function OpenUpdateDownloadPage(arg1:number):Promise<string>;

export function PickCoverImage():Promise<string>;

export function PickDirectory():Promise<string>;

export function PlayGame(arg1:number):Promise<string>;

export function PreviewCoverFile(arg1:string):Promise<string>;

export function ProvideUpdateFile(arg1:number):Promise<void>;

export function PurgeDeleted():Promise<number>;

export function RemoveDuplicate(arg1:number):Promise<void>;

export function RemoveGame(arg1:number,arg2:boolean):Promise<void>;

export function RemoveGameFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemoveScanPath(arg1:string):Promise<void>;

export function RenameGame(arg1:number,arg2:string):Promise<void>;

export function RescanDirectory(arg1:context.Context,arg2:string,arg3:Array<string>):Promise<boolean>;

export function RestoreGame(arg1:number):Promise<void>;

export function RevertCover(arg1:number):Promise<void>;

export function ScanDirectory(arg1:string,arg2:boolean):Promise<void>;

export function SearchF95Zone(arg1:string):Promise<Array<main.F95SearchResult>>;

export function SearchGames(arg1:string):Promise<Array<main.DesktopGameSummary>>;

export function SetCoverLocked(arg1:number,arg2:boolean):Promise<void>;

export function SetCoverSources(arg1:boolean,arg2:boolean):Promise<void>;

export function SetGameCover(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetGameCoverFromFile(arg1:number,arg2:string):Promise<void>;

export function SetGameStatus(arg1:number,arg2:string):Promise<void>;

export function SetGameWinePrefix(arg1:number,arg2:string):Promise<void>;

export function SetOrganizeInstalls(arg1:boolean):Promise<void>;

export function SetSteamGridDBKey(arg1:string):Promise<void>;

export function SetUpdateConcurrency(arg1:number):Promise<void>;

export function SyncAllGames(arg1:boolean):Promise<void>;

export function SyncSingleGame(arg1:number):Promise<void>;

export function UpgradeCovers():Promise<void>;
