// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function AddGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function AddGameFromF95Zone(arg1:string,arg2:string,arg3:string):Promise<number>;

export function AddScanPath(arg1:string):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function CancelGameUpdate():Promise<boolean>;

export function CheckDependencies():Promise<Array<main.DependencyStatus>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DetectGame(arg1:string):Promise<main.DetectionResult>;

export function DownloadAllUpdates():Promise<void>;

export function DownloadGameUpdate(arg1:number):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function EditGame(arg1:number,arg2:main.EditGameFields):Promise<void>;

export function FindDuplicateGames():Promise<Array<main.DuplicateGroup>>;

export function GetAllDownloadLinks():Promise<Array<main.DesktopDownloadLinkWithGame>>;

export function GetCachedCovers(arg1:Array<number>):Promise<Record<number, string>>;

export function GetConfigDir():Promise<string>;

export function GetCookieStatus():Promise<string>;

export function GetDbPath():Promise<string>;

export function GetGameCount():Promise<number>;

export function GetGameCountByStatus():Promise<Array<main.StatusCount>>;

export function GetGameDetail(arg1:number):Promise<main.DesktopGameDetail>;

export function GetGameDownloadLinks(arg1:number):Promise<Array<main.DesktopDownloadLink>>;

export function GetGameDownloadLinksForUpdate(arg1:number):Promise<db.DownloadLink>;

export function GetGames():Promise<Array<main.DesktopGameSummary>>;

export function GetGamesWithDownloadLinks():Promise<Array<main.DesktopGameSummary>>;

export function GetScanPaths():Promise<Array<string>>;

export function GetStartupError():Promise<string>;

export function GetThreadPreview(arg1:string):Promise<main.ThreadPreview>;

export function GetUpdatableCount():Promise<number>;

export function GetUpdatableGames():Promise<Array<main.DesktopGameSummary>>;

export function GetVersion():Promise<string>;

export function ListDeletedGames():Promise<Array<main.DesktopGameSummary>>;

export function OpenDownloadURL(arg1:number):Promise<void>;

export function PickDirectory():Promise<string>;

export function PlayGame(arg1:number):Promise<string>;

export function PurgeDeleted():Promise<number>;

export function RemoveGame(arg1:number,arg2:boolean):Promise<void>;

export function RemoveScanPath(arg1:string):Promise<void>;

export function RenameGame(arg1:number,arg2:string):Promise<void>;

export function RescanDirectory(arg1:string):Promise<void>;

export function RestoreGame(arg1:number):Promise<void>;

export function ScanDirectory(arg1:string):Promise<void>;

export function SearchF95Zone(arg1:string):Promise<Array<main.F95SearchResult>>;

export function SearchGames(arg1:string):Promise<Array<main.DesktopGameSummary>>;

export function SetGameStatus(arg1:number,arg2:string):Promise<void>;

export function SetGameWinePrefix(arg1:number,arg2:string):Promise<void>;

export function SyncAllGames():Promise<void>;

export function SyncSingleGame(arg1:number):Promise<void>;
