// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddGame'](arg1, arg2, arg3, arg4);
}

export function AddGameFromF95Zone(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddGameFromF95Zone'](arg1, arg2, arg3);
}

export function AddScanPath(arg1) {
  return window['go']['main']['App']['AddScanPath'](arg1);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CacheCover(arg1, arg2) {
  return window['go']['main']['App']['CacheCover'](arg1, arg2);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DetectGame(arg1) {
  return window['go']['main']['App']['DetectGame'](arg1);
}

export function DownloadAllUpdates() {
  return window['go']['main']['App']['DownloadAllUpdates']();
}

export function DownloadGameUpdate(arg1) {
  return window['go']['main']['App']['DownloadGameUpdate'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function EditGame(arg1, arg2) {
  return window['go']['main']['App']['EditGame'](arg1, arg2);
}

export function FindDuplicateGames() {
  return window['go']['main']['App']['FindDuplicateGames']();
}

export function GetAllDownloadLinks() {
  return window['go']['main']['App']['GetAllDownloadLinks']();
}

export function GetCachedCover(arg1) {
  return window['go']['main']['App']['GetCachedCover'](arg1);
}

export function GetCachedCovers(arg1) {
  return window['go']['main']['App']['GetCachedCovers'](arg1);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetCookieStatus() {
  return window['go']['main']['App']['GetCookieStatus']();
}

export function GetCoverPath(arg1) {
  return window['go']['main']['App']['GetCoverPath'](arg1);
}

export function GetDbPath() {
  return window['go']['main']['App']['GetDbPath']();
}

export function GetGameCount() {
  return window['go']['main']['App']['GetGameCount']();
}

export function GetGameCountByStatus() {
  return window['go']['main']['App']['GetGameCountByStatus']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function GetGameDownloadLinks(arg1) {
  return window['go']['main']['App']['GetGameDownloadLinks'](arg1);
}

export function GetGameDownloadLinksForUpdate(arg1) {
  return window['go']['main']['App']['GetGameDownloadLinksForUpdate'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetGamesWithDownloadLinks() {
  return window['go']['main']['App']['GetGamesWithDownloadLinks']();
}

export function GetScanPaths() {
  return window['go']['main']['App']['GetScanPaths']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetThreadPreview(arg1) {
  return window['go']['main']['App']['GetThreadPreview'](arg1);
}

export function GetUpdatableCount() {
  return window['go']['main']['App']['GetUpdatableCount']();
}

export function GetUpdatableGames() {
  return window['go']['main']['App']['GetUpdatableGames']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDeletedGames() {
  return window['go']['main']['App']['ListDeletedGames']();
}

export function OpenDownloadURL(arg1) {
  return window['go']['main']['App']['OpenDownloadURL'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PlayGame(arg1) {
  return window['go']['main']['App']['PlayGame'](arg1);
}

export function PurgeDeleted() {
  return window['go']['main']['App']['PurgeDeleted']();
}

export function RemoveGame(arg1, arg2) {
  return window['go']['main']['App']['RemoveGame'](arg1, arg2);
}

export function RemoveScanPath(arg1) {
  return window['go']['main']['App']['RemoveScanPath'](arg1);
}

export function RenameGame(arg1, arg2) {
  return window['go']['main']['App']['RenameGame'](arg1, arg2);
}

export function RestoreGame(arg1) {
  return window['go']['main']['App']['RestoreGame'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SearchF95Zone(arg1) {
  return window['go']['main']['App']['SearchF95Zone'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SetGameStatus(arg1, arg2) {
  return window['go']['main']['App']['SetGameStatus'](arg1, arg2);
}

export function SetGameWinePrefix(arg1, arg2) {
  return window['go']['main']['App']['SetGameWinePrefix'](arg1, arg2);
}

export function SyncAllGames(arg1) {
  return window['go']['main']['App']['SyncAllGames'](arg1);
}

export function SyncSingleGame(arg1) {
  return window['go']['main']['App']['SyncSingleGame'](arg1);
}
